development:
  clients:
    default:
      database: geopolitical_spec_development
      hosts:
        - <%= ENV.fetch("MONGODB_HOST", "localhost:27017") %>
test:
  clients:
    default:
      database: geopolitical_spec
      hosts:
        - <%= ENV.fetch("MONGODB_HOST", "localhost:27017") %>
